---
kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    registry: atdr-writer.meo.ws
    username:
      from_secret: atdr_user
    password:
      from_secret: atdr_pass
    repo: atdr-writer.meo.ws/archiveteam/warrior-dockerfile
    dockerfile: Dockerfile
    purge: true
    auto_tag: false
    tags:
    - latest
