apiVersion: v1
kind: Service
metadata:
  name: warrior
spec:
  type: NodePort
  selector:
    app: warrior
  ports:
    - nodePort: 30163
      port: 8001
      targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: warrior
  labels:
    app: warrior
spec:
  selector:
    matchLabels:
      app: warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: warrior
    spec:
      containers:
      - image: atdr.meo.ws/archiveteam/warrior-dockerfile:latest
        name: warrior
        resources: {}
        env:
        - name: DOWNLOADER
          value: kubernetes
        - name: SELECTED_PROJECT
          value: auto
        ports:
        - containerPort: 8001
