apiVersion: v1
kind: Service
metadata:
  name: warrior
spec:
  type: NodePort
  selector:
    app: warrior
  ports:
    - nodePort: 30163
      port: 8001
      targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: warrior
  labels:
    app: warrior
spec:
  selector:
    matchLabels:
      app: warrior
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: warrior
    spec:
      volumes:
      - name: warrior-data
        emptyDir: {}
      containers:
      - image: docker.io/kjoconnor/archive-team-warrior:latest
        name: warrior
        ports:
        - containerPort: 8001
        volumeMounts:
        - name: warrior-data
          mountPath: /home/warrior
      initContainers:
        - name: create-dirs
          image: busybox
          command: [ "mkdir", "/home/warrior/projects", "/home/warrior/assets" ]
          volumeMounts:
          - name: warrior-data
            mountPath: /home/warrior
        - name: chmod
          image: busybox
          command: [ "chmod", "-R", "777", "/home/warrior" ]
          volumeMounts:
          - name: warrior-data
            mountPath: /home/warrior
